server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-services
          uri: http://localhost:8001
          predicates:
            - Path=/products/**

        - id:  orders-services
          uri: http://localhost:8002
          predicates:
            - Path=/orders/**

        - id: payments-services
          uri: http://localhost:8003
          predicates:
            - Path=/pay/**
        
        - id: users-services
          uri: http://localhost:8004
          predicates:
            - Path=/users/**