server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-services
          #uri: http://localhost:8001
          uri: lb://msvc-products
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter

        - id:  orders-services
          uri: lb://msvc-orders
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter

        - id: payments-services
          uri: lb://msvc-pay
          predicates:
            - Path=/pay/**
          filters:
            - AuthFilter
        
        - id: users-services
          uri: lb://msvc-users
          predicates:
            - Path=/users/**