server:
  port: 8003

spring:
  application:
    name: msvc-pay
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
