server:
  port: 8081
Spring:
  cloud:
    config:
      server:
        git:
          default-label: routers
          uri: https://github.com/Raulcudris/Ecommerce.git
          search-paths: config-data
  application:
    name: config-service